name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Configure Git
        run: |
          git config user.name "Publisher"
          git config user.email "publisher@users.noreply.github.com"
      - name: Build website
        run: npm install
      - name: Build website
        run: npm run build
      - name: Switch to branch 'gh-pages'
        run: |
          git branch -f gh-pages HEAD
          git checkout gh-pages
      - run: |
          git add -f build/
          git commit -m "Publish"
          git push -f origin `git subtree split -P build`:refs/heads/gh-pages
